import raw from './facebook-posts.json';

export type FacebookPost = {
  id: string;
  /** Post text as written on the Page. Posts without text are dropped at fetch time. */
  message: string;
  /** ISO 8601, as Graph returns it. */
  createdTime: string;
  permalink: string | null;
  /** Graph's full_picture CDN URL. These expire — treat as best-effort, not permanent. */
  image: string | null;
};

/**
 * Generated by `pnpm run facebook` — do not hand-edit facebook-posts.json.
 *
 * This is the Page's own published posts, so it is our content to republish.
 * Customer reviews are a different matter and deliberately stay out of here:
 * see the note in testimonials.ts.
 */
export const facebookPosts: FacebookPost[] = raw as FacebookPost[];

/** Newest first. The JSON is already sorted; this keeps callers independent of that. */
export function postsByNewest(posts: FacebookPost[] = facebookPosts): FacebookPost[] {
  return [...posts].sort((a, b) => Date.parse(b.createdTime) - Date.parse(a.createdTime));
}

/** Newest `count` posts — what the homepage section shows. */
export function recentPosts(count: number, posts: FacebookPost[] = facebookPosts): FacebookPost[] {
  return postsByNewest(posts).slice(0, count);
}

/** Thai and English both read well with the Buddhist-era-free Gregorian date. */
export function formatPostDate(iso: string, lang: 'th' | 'en'): string {
  return new Date(iso).toLocaleDateString(lang === 'th' ? 'th-TH' : 'en-GB', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}
